version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/dynamic:/dynamic
      - /opt/traefik/letsencrypt:/letsencrypt
    networks:
      - portainer_network

  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_network
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:

networks:
  portainer_network:
    driver: overlay